name: Luassert

on: [push, pull_request]

jobs:

  busted:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.4", "5.3", "5.2", "5.1", "luajit", "luajit-openresty"]
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup ‘lua’
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: ${{ matrix.luaVersion }}
    - name: Setup ‘luarocks’
      uses: leafo/gh-actions-luarocks@v4
    - name: Setup dependencies
      run: |
        luarocks install busted
        luarocks install luacov
        luarocks remove luassert --force
    - name: Cache Lua machinery
      uses: actions/cache@v2
      with:
        path: |
          .install
          .lua
          .luarocks
        key: lua-${{ matrix.luaVersion }}-${{ hashFiles('.github/workflows/luassert.yml') }}
    - name: Build
      run: |
        luarocks make
    - name: Run tests
      run: busted -v
